name: EKS CI/CD Blue-Green Pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER: my-demo-cluster1
  ECR_REPO: plot-listing
  IMAGE_TAG: latest
  GREEN_DEPLOYMENT: my-app-green
  SERVICE_NAME: service-2048

jobs:

  build-and-deploy-green:
    name: Build → Push → Deploy Green → Test → Switch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Docker Image
        run: |
          docker build -t $ECR_REPO:$IMAGE_TAG .
          docker tag $ECR_REPO:$IMAGE_TAG ${{ steps.login-ecr.outputs.registry }}/${ECR_REPO}:${IMAGE_TAG}
          docker push ${{ steps.login-ecr.outputs.registry }}/${ECR_REPO}:${IMAGE_TAG}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name $EKS_CLUSTER --region $AWS_REGION

      - name: Deploy Green Deployment
        run: |
          sed -i "s|IMAGE_URI|${{ steps.login-ecr.outputs.registry }}/${ECR_REPO}:${IMAGE_TAG}|g" k8s/deployment-green.yaml
          kubectl apply -f k8s/deployment-green.yaml

      - name: Wait for Green Deployment Rollout
        run: |
          kubectl rollout status deployment/$GREEN_DEPLOYMENT --timeout=180s

      - name: Run Integration Tests on Green
        run: |
          chmod +x tests/run-tests.sh
          ./tests/run-tests.sh

      - name: Switch Service to Green
        run: |
          kubectl patch service $SERVICE_NAME -p '{"spec":{"selector":{"app":"my-app","version":"green"}}}'

      - name: Optional: Delete Blue Deployment
        run: |
          kubectl delete deployment my-app-blue || echo "Blue deployment not found, skipping"


  # ---------------------------- SECOND JOB ---------------------------- #

  integration-tests:
    name: Full Integration Test Suite
    runs-on: ubuntu-latest
    needs: build-and-deploy-green     # Wait for Green deployment job to finish

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install pytest requests

      - name: Run Integration Tests
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          POSTHOG_API: ${{ secrets.POSTHOG_API }}
          POSTHOG_KEY: ${{ secrets.POSTHOG_KEY }}
        run: pytest -v --maxfail=1
